import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#5d4201',
        'on-secondary': '#ffffff',
        'outline-variant': '#c6c6cd',
        'on-tertiary-fixed-variant': '#574425',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#dec29a',
        'on-primary-fixed-variant': '#3f465c',
        'primary': '#000000',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#261900',
        'on-surface': '#0b1c30',
        'on-tertiary-container': '#98805d',
        'on-primary': '#ffffff',
        'on-surface-variant': '#45464d',
        'surface': '#f8f9ff',
        'error': '#ba1a1a',
        'tertiary': '#000000',
        'surface-container-high': '#dce9ff',
        'surface-container': '#e5eeff',
        'secondary-fixed': '#ffdea5',
        'tertiary-fixed': '#fcdeb5',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#131b2e',
        'on-primary-container': '#7c839b',
        'surface-variant': '#d3e4fe',
        'inverse-on-surface': '#eaf1ff',
        'primary-fixed-dim': '#bec6e0',
        'on-secondary-container': '#785a1a',
        'primary-container': '#131b2e',
        'surface-dim': '#cbdbf5',
        'secondary-fixed-dim': '#e9c176',
        'on-background': '#0b1c30',
        'tertiary-container': '#271901',
        'primary-fixed': '#dae2fd',
        'on-tertiary': '#ffffff',
        'outline': '#76777d',
        'on-tertiary-fixed': '#271901',
        'secondary': '#775a19',
        'secondary-container': '#fed488',
        'inverse-surface': '#213145',
        'on-error': '#ffffff',
        'surface-tint': '#565e74',
        'surface-container-low': '#eff4ff',
        'inverse-primary': '#bec6e0',
        'error-container': '#ffdad6',
        'background': '#f8f9ff',
        'surface-container-highest': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        md: '16px',
        lg: '24px',
        'container-max': '1440px',
        xs: '4px',
        sm: '8px',
        xl: '32px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config
